/**
 * Traceability Matrix:
 * - T048: Disclaimer xuất hiện trên AI reports.
 * - SPEC FR-21: AI Disclaimer must be visible on generated outputs.
 */

import React from 'react';
import { render, screen } from '@testing-library/react';
import { describe, it, expect } from 'vitest';
import AiDisclaimer from '../../../../src/components/ai/AiDisclaimer';

describe('AiDisclaimer Component', () => {
  it('should render the default disclaimer text (FR-21)', () => {
    render(<AiDisclaimer />);
    const disclaimer = screen.getByTestId('ai-disclaimer');
    expect(disclaimer).toBeInTheDocument();
    expect(screen.getByText(/generated by an Artificial Intelligence system/i)).toBeInTheDocument();
    expect(screen.getByText(/does not replace official human grading/i)).toBeInTheDocument();
  });

  it('should render custom text if provided', () => {
    render(<AiDisclaimer customText="This is a custom AI note." />);
    expect(screen.getByText('This is a custom AI note.')).toBeInTheDocument();
    expect(screen.queryByText(/generated by an Artificial Intelligence system/i)).not.toBeInTheDocument();
  });

  it('should apply additional CSS classes if provided', () => {
    render(<AiDisclaimer className="mt-5 custom-class" />);
    const disclaimer = screen.getByTestId('ai-disclaimer');
    expect(disclaimer).toHaveClass('ai-disclaimer');
    expect(disclaimer).toHaveClass('mt-5');
    expect(disclaimer).toHaveClass('custom-class');
  });
});
