/**
 * Traceability Matrix:
 * - T043: Hiển thị transcript, band score, criteria, pronunciation limitation notice nếu có, disclaimer.
 * - SPEC FR-07: AI pronunciation grading might not capture nuances; warning notice is required.
 * - SPEC FR-21: Display processing state visually using Bootstrap components.
 * - SPEC STU-09: Disclaimer must be shown to users when viewing AI generated content.
 */

import React from 'react';
import { render, screen } from '@testing-library/react';
import { describe, it, expect } from 'vitest';
import SpeakingAiReport from '../../../../src/components/ai/SpeakingAiReport';

describe('SpeakingAiReport Component', () => {
  const mockReportData = {
    overallScore: 6.5,
    criteria: {
      fluencyCoherence: 6.0,
      lexicalResource: 7.0,
      grammaticalRange: 6.5,
      pronunciation: 6.0
    },
    transcript: "Well, I think technology has both positive and negative impacts on our lives. For example, it makes communication much easier."
  };

  it('should render nothing if reportData is null', () => {
    const { container } = render(<SpeakingAiReport reportData={null} />);
    expect(container.firstChild).toBeNull();
  });

  it('should render the Speaking feedback report header and overall score', () => {
    render(<SpeakingAiReport reportData={mockReportData} />);
    expect(screen.getByText('IELTS Speaking AI Feedback')).toBeInTheDocument();
    expect(screen.getByTestId('speaking-overall-score')).toHaveTextContent('Band 6.5');
  });

  it('should render all 4 speaking criteria correctly', () => {
    render(<SpeakingAiReport reportData={mockReportData} />);
    expect(screen.getByText('Fluency & Coherence')).toBeInTheDocument();
    expect(screen.getByText('Lexical Resource')).toBeInTheDocument();
    expect(screen.getByText('Grammatical Range & Accuracy')).toBeInTheDocument();
    expect(screen.getByText('Pronunciation')).toBeInTheDocument();

    // Check specific scores
    expect(screen.getByText('7')).toBeInTheDocument(); // Lexical
  });

  it('should render the transcript text', () => {
    render(<SpeakingAiReport reportData={mockReportData} />);
    expect(screen.getByTestId('speech-transcript')).toHaveTextContent(/technology has both positive and negative impacts/i);
  });

  it('should handle missing transcript gracefully', () => {
    const emptyData = { ...mockReportData, transcript: null };
    render(<SpeakingAiReport reportData={emptyData} />);
    expect(screen.getByTestId('speech-transcript')).toHaveTextContent(/No transcript provided/i);
  });

  it('should render pronunciation warning when showPronunciationWarning is true', () => {
    render(<SpeakingAiReport reportData={mockReportData} showPronunciationWarning={true} />);
    const warning = screen.getByTestId('pronunciation-warning');
    expect(warning).toBeInTheDocument();
    expect(warning).toHaveTextContent(/AI assessment of pronunciation may be limited/i);
  });

  it('should NOT render pronunciation warning when showPronunciationWarning is false', () => {
    render(<SpeakingAiReport reportData={mockReportData} showPronunciationWarning={false} />);
    const warning = screen.queryByTestId('pronunciation-warning');
    expect(warning).not.toBeInTheDocument();
  });

  it('should ALWAYS render the AI disclaimer', () => {
    render(<SpeakingAiReport reportData={mockReportData} />);
    const disclaimer = screen.getByTestId('ai-disclaimer');
    expect(disclaimer).toBeInTheDocument();
    expect(disclaimer).toHaveTextContent(/Disclaimer: This feedback is generated by AI/i);
  });
});
