/**
 * Traceability Matrix:
 * - T042: Hiển thị band score, 4 criteria, highlights, suggestions, disclaimer. Label Task 1/Task 2 đúng.
 * - SPEC FR-21: Receive real-time processing status (and display final report). AI disclaimer is required.
 * - SPEC STU-09: Disclaimer must be shown to users when viewing AI generated content.
 */

import React from 'react';
import { render, screen } from '@testing-library/react';
import { describe, it, expect } from 'vitest';
import WritingAiReport from '../../../../src/components/ai/WritingAiReport';

describe('WritingAiReport Component', () => {
  const mockReportData = {
    overallScore: 7.0,
    criteria: {
      taskAchievement: 7.0,
      coherenceCohesion: 6.5,
      lexicalResource: 7.5,
      grammaticalRange: 7.0
    },
    highlights: ['Good vocabulary usage', 'Clear paragraphing'],
    suggestions: ['Improve complex sentence structures']
  };

  it('should render nothing if reportData is null', () => {
    const { container } = render(<WritingAiReport reportData={null} taskType={1} />);
    expect(container.firstChild).toBeNull();
  });

  it('should render Task 1 label and "Task Achievement" when taskType is 1', () => {
    render(<WritingAiReport reportData={mockReportData} taskType={1} />);
    expect(screen.getByText('IELTS Writing Task 1 AI Feedback')).toBeInTheDocument();
    expect(screen.getByText('Task Achievement')).toBeInTheDocument();
    expect(screen.queryByText('Task Response')).not.toBeInTheDocument();
  });

  it('should render Task 2 label and "Task Response" when taskType is 2', () => {
    const task2Data = {
      ...mockReportData,
      criteria: {
        taskResponse: 7.0,
        coherenceCohesion: 6.5,
        lexicalResource: 7.5,
        grammaticalRange: 7.0
      }
    };
    render(<WritingAiReport reportData={task2Data} taskType={2} />);
    expect(screen.getByText('IELTS Writing Task 2 AI Feedback')).toBeInTheDocument();
    expect(screen.getByText('Task Response')).toBeInTheDocument();
    expect(screen.queryByText('Task Achievement')).not.toBeInTheDocument();
  });

  it('should render overall score correctly', () => {
    render(<WritingAiReport reportData={mockReportData} taskType={1} />);
    expect(screen.getByTestId('overall-score')).toHaveTextContent('Band 7');
  });

  it('should render all 4 criteria correctly', () => {
    render(<WritingAiReport reportData={mockReportData} taskType={1} />);
    expect(screen.getByText('6.5')).toBeInTheDocument();
    expect(screen.getByText('7.5')).toBeInTheDocument();
  });

  it('should render highlights and suggestions correctly', () => {
    render(<WritingAiReport reportData={mockReportData} taskType={1} />);
    expect(screen.getByText('Good vocabulary usage')).toBeInTheDocument();
    expect(screen.getByText('Clear paragraphing')).toBeInTheDocument();
    expect(screen.getByText('Improve complex sentence structures')).toBeInTheDocument();
  });

  it('should handle missing highlights or suggestions gracefully', () => {
    const emptyData = { ...mockReportData, highlights: [], suggestions: null };
    render(<WritingAiReport reportData={emptyData} taskType={1} />);
    expect(screen.getByText('No highlights provided.')).toBeInTheDocument();
    expect(screen.getByText('No suggestions provided.')).toBeInTheDocument();
  });

  it('should ALWAYS render the AI disclaimer', () => {
    render(<WritingAiReport reportData={mockReportData} taskType={1} />);
    const disclaimer = screen.getByTestId('ai-disclaimer');
    expect(disclaimer).toBeInTheDocument();
    expect(disclaimer).toHaveTextContent(/Disclaimer: This feedback is generated by AI/i);
  });
});
