import React from 'react';
import PropTypes from 'prop-types';

/**
 * Standardized Component for displaying the AI Disclaimer.
 * Must be included at the bottom of all AI-generated reports or content.
 */
const AiDisclaimer = ({ customText, className }) => {
  // EARS[Constraint]: System MUST clarify that this is AI generated content (FR-21)
  const defaultText = "This feedback is generated by an Artificial Intelligence system. While it aims to be accurate and helpful, it does not replace official human grading and may contain errors. Please use it as a reference guide.";
  const displayText = customText || defaultText;

  return (
    <div className={`ai-disclaimer text-muted small p-2 bg-light border-top ${className || ''}`} data-testid="ai-disclaimer">
      <div className="d-flex align-items-start">
        <i className="bi bi-info-circle-fill text-secondary me-2 mt-1"></i>
        <em className="text-secondary" style={{ lineHeight: '1.4' }}>
          {displayText}
        </em>
      </div>
    </div>
  );
};

AiDisclaimer.propTypes = {
  customText: PropTypes.string,
  className: PropTypes.string
};

export default AiDisclaimer;
