import React from 'react';
import PropTypes from 'prop-types';

/**
 * Component to display the AI speaking feedback report.
 */
const SpeakingAiReport = ({ reportData, showPronunciationWarning = false }) => {
  // EARS[State]: WHEN reportData is null or undefined, THEN return null
  if (!reportData) {
    return null;
  }

  const { overallScore, criteria, transcript } = reportData;

  return (
    <div className="card shadow-sm border-info mt-4" data-testid="speaking-ai-report">
      <div className="card-header bg-info text-dark d-flex justify-content-between align-items-center">
        <h5 className="mb-0">
          <i className="bi bi-mic-fill me-2"></i>
          IELTS Speaking AI Feedback
        </h5>
        <span className="badge bg-light text-dark fs-5 border border-secondary" data-testid="speaking-overall-score">
          Band {overallScore || 'N/A'}
        </span>
      </div>

      <div className="card-body">
        {/* EARS[Constraint]: WHEN showPronunciationWarning is true, THEN render pronunciation limitation alert */}
        {showPronunciationWarning && (
          <div className="alert alert-warning d-flex align-items-center p-3 mb-4" role="alert" data-testid="pronunciation-warning">
            <i className="bi bi-exclamation-triangle-fill fs-4 me-3"></i>
            <div>
              <strong>Note on Pronunciation:</strong> AI assessment of pronunciation may be limited by audio quality and lacks human nuance. It should be used as a reference only.
            </div>
          </div>
        )}

        <h6 className="fw-bold mb-3 border-bottom pb-2">Scoring Criteria</h6>
        <div className="row mb-4">
          <div className="col-md-6 mb-2">
            <div className="d-flex justify-content-between p-2 bg-light rounded">
              <span>Fluency & Coherence</span>
              <span className="fw-bold text-info">{criteria?.fluencyCoherence || 'N/A'}</span>
            </div>
          </div>
          <div className="col-md-6 mb-2">
            <div className="d-flex justify-content-between p-2 bg-light rounded">
              <span>Lexical Resource</span>
              <span className="fw-bold text-info">{criteria?.lexicalResource || 'N/A'}</span>
            </div>
          </div>
          <div className="col-md-6 mb-2">
            <div className="d-flex justify-content-between p-2 bg-light rounded">
              <span>Grammatical Range & Accuracy</span>
              <span className="fw-bold text-info">{criteria?.grammaticalRange || 'N/A'}</span>
            </div>
          </div>
          <div className="col-md-6 mb-2">
            <div className="d-flex justify-content-between p-2 bg-light rounded">
              <span>Pronunciation</span>
              <span className="fw-bold text-info">{criteria?.pronunciation || 'N/A'}</span>
            </div>
          </div>
        </div>

        <div className="mb-3">
          <h6 className="fw-bold text-secondary mb-2">
            <i className="bi bi-card-text me-2"></i>Transcript
          </h6>
          <div
            className="bg-light p-3 rounded border overflow-auto"
            style={{ maxHeight: '200px' }}
            data-testid="speech-transcript"
          >
            {transcript ? (
              <p className="mb-0" style={{ whiteSpace: 'pre-wrap' }}>{transcript}</p>
            ) : (
              <p className="text-muted small italic mb-0">No transcript provided or audio could not be recognized.</p>
            )}
          </div>
        </div>
      </div>

      {/* EARS[Constraint]: System MUST render the AI Disclaimer at the bottom of the report */}
      <div className="card-footer bg-light text-muted small text-center" data-testid="ai-disclaimer">
        <i className="bi bi-info-circle me-1"></i>
        <em>Disclaimer: This feedback is generated by AI and is for reference purposes only. It does not replace professional human evaluation.</em>
      </div>
    </div>
  );
};

SpeakingAiReport.propTypes = {
  reportData: PropTypes.shape({
    overallScore: PropTypes.number,
    criteria: PropTypes.shape({
      fluencyCoherence: PropTypes.number,
      lexicalResource: PropTypes.number,
      grammaticalRange: PropTypes.number,
      pronunciation: PropTypes.number,
    }),
    transcript: PropTypes.string
  }),
  showPronunciationWarning: PropTypes.bool
};

export default SpeakingAiReport;
