import React from 'react';
import PropTypes from 'prop-types';

/**
 * Component to display the AI writing feedback report.
 */
const WritingAiReport = ({ reportData, taskType }) => {
  // EARS[State]: WHEN reportData is null or undefined, THEN return null
  if (!reportData) {
    return null;
  }

  const { overallScore, criteria, highlights, suggestions } = reportData;
  const taskLabel = taskType === 1 ? 'Task 1' : 'Task 2';

  return (
    <div className="card shadow-sm border-primary mt-4" data-testid="writing-ai-report">
      <div className="card-header bg-primary text-white d-flex justify-content-between align-items-center">
        <h5 className="mb-0">
          <i className="bi bi-robot me-2"></i>
          IELTS Writing {taskLabel} AI Feedback
        </h5>
        <span className="badge bg-light text-primary fs-5" data-testid="overall-score">
          Band {overallScore || 'N/A'}
        </span>
      </div>

      <div className="card-body">
        <h6 className="fw-bold mb-3 border-bottom pb-2">Scoring Criteria</h6>
        <div className="row mb-4">
          <div className="col-md-6 mb-2">
            <div className="d-flex justify-content-between p-2 bg-light rounded">
              <span>{taskType === 1 ? 'Task Achievement' : 'Task Response'}</span>
              <span className="fw-bold text-primary">{criteria?.taskAchievement || criteria?.taskResponse || 'N/A'}</span>
            </div>
          </div>
          <div className="col-md-6 mb-2">
            <div className="d-flex justify-content-between p-2 bg-light rounded">
              <span>Coherence & Cohesion</span>
              <span className="fw-bold text-primary">{criteria?.coherenceCohesion || 'N/A'}</span>
            </div>
          </div>
          <div className="col-md-6 mb-2">
            <div className="d-flex justify-content-between p-2 bg-light rounded">
              <span>Lexical Resource</span>
              <span className="fw-bold text-primary">{criteria?.lexicalResource || 'N/A'}</span>
            </div>
          </div>
          <div className="col-md-6 mb-2">
            <div className="d-flex justify-content-between p-2 bg-light rounded">
              <span>Grammatical Range & Accuracy</span>
              <span className="fw-bold text-primary">{criteria?.grammaticalRange || 'N/A'}</span>
            </div>
          </div>
        </div>

        <div className="row">
          <div className="col-md-6 mb-3">
            <h6 className="fw-bold text-success mb-2">
              <i className="bi bi-check-circle-fill me-2"></i>Highlights
            </h6>
            {highlights && highlights.length > 0 ? (
              <ul className="list-group list-group-flush border rounded">
                {highlights.map((item, index) => (
                  <li key={index} className="list-group-item bg-light border-0 mb-1 rounded">{item}</li>
                ))}
              </ul>
            ) : (
              <p className="text-muted small italic">No highlights provided.</p>
            )}
          </div>

          <div className="col-md-6 mb-3">
            <h6 className="fw-bold text-warning mb-2">
              <i className="bi bi-exclamation-circle-fill me-2"></i>Suggestions for Improvement
            </h6>
            {suggestions && suggestions.length > 0 ? (
              <ul className="list-group list-group-flush border rounded">
                {suggestions.map((item, index) => (
                  <li key={index} className="list-group-item bg-light border-0 mb-1 rounded">{item}</li>
                ))}
              </ul>
            ) : (
              <p className="text-muted small italic">No suggestions provided.</p>
            )}
          </div>
        </div>
      </div>

      {/* EARS[Constraint]: System MUST render the AI Disclaimer at the bottom of the report */}
      <div className="card-footer bg-light text-muted small text-center" data-testid="ai-disclaimer">
        <i className="bi bi-info-circle me-1"></i>
        <em>Disclaimer: This feedback is generated by AI and is for reference purposes only. It does not replace professional human evaluation.</em>
      </div>
    </div>
  );
};

WritingAiReport.propTypes = {
  reportData: PropTypes.shape({
    overallScore: PropTypes.number,
    criteria: PropTypes.shape({
      taskAchievement: PropTypes.number,
      taskResponse: PropTypes.number,
      coherenceCohesion: PropTypes.number,
      lexicalResource: PropTypes.number,
      grammaticalRange: PropTypes.number,
    }),
    highlights: PropTypes.arrayOf(PropTypes.string),
    suggestions: PropTypes.arrayOf(PropTypes.string)
  }),
  taskType: PropTypes.oneOf([1, 2]).isRequired
};

export default WritingAiReport;
